In [1]:
import torch

In [2]:
x = torch.tensor([1,2,3])
y = torch.tensor([10,10,10])

print(x + y)

tensor([11, 12, 13])


In [3]:
a = torch.tensor([1,2,3])
print(a + 10)

tensor([11, 12, 13])


In [5]:
b = torch.tensor([
    [1,2,3],
    [4,5,6]
])

c = torch.tensor([10,20,30])

print(b + c)

tensor([[11, 22, 33],
        [14, 25, 36]])


In [ ]:
d = torch.tensor([[1,2,3],[4,5,6]])
e = torch.tensor([10,20])

e_col = e.reshape(2,1)

print(e_col)

print(d + e_col)

tensor([[10],
        [20]])
tensor([[11, 12, 13],
        [24, 25, 26]])


: 