In [1]:
import torch

In [2]:
vector = torch.tensor([1,2,3])
scalar = torch.tensor(10)

print(vector + scalar)

tensor([11, 12, 13])


In [3]:
matrix = torch.tensor([
    [1,2,3],
    [4,5,6]
])

row = torch.tensor([10,20,30])

print(matrix + row)

tensor([[11, 22, 33],
        [14, 25, 36]])


In [4]:
matrix = torch.tensor([
    [1,2,3],
    [4,5,6]
])

column = torch.tensor([[10],
                       [20]
                       ])

print(matrix + column)

tensor([[11, 12, 13],
        [24, 25, 26]])


In [ ]:
A = torch.rand(2,3)
B = torch.rand(2,3)

print(A + B)

tensor([[1.2898, 0.4293, 1.0656],
        [0.2428, 1.1115, 1.5001]])


: 