In [10]:
import torch

In [11]:
x = torch.tensor([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

print(x)
print(x.shape)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
torch.Size([3, 3])


In [12]:
print(x[0,0])

tensor(10)


In [13]:
print(x[1,2])

tensor(60)


In [14]:
print(x[0])

tensor([10, 20, 30])


In [15]:
print(x[1])

tensor([40, 50, 60])


In [16]:
print(x[:,0])

tensor([10, 40, 70])


In [17]:
print(x[:,1])

tensor([20, 50, 80])


In [18]:
print(x)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [19]:
print(x[0:2, 1:3])

tensor([[20, 30],
        [50, 60]])


In [20]:
v = torch.tensor([5,10,15,20,25])

In [21]:
print(v[0])

tensor(5)


In [22]:
print(v[2])

tensor(15)


In [23]:
print(v[1:4])

tensor([10, 15, 20])


In [24]:
t = torch.tensor([
    [[1,2],[3,4]],
    [[5,6],[7,8]]

])

In [25]:
print(t[0])

tensor([[1, 2],
        [3, 4]])


In [26]:
print(t[0,1])

tensor([3, 4])


In [27]:
print(t[1,0,1])

tensor(6)


In [28]:
t.shape

torch.Size([2, 2, 2])

In [29]:
print(t)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [30]:
practice = torch.tensor([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

In [32]:
print(practice[0])

tensor([1, 2, 3, 4])


In [33]:
print(practice[:, 1])

tensor([ 2,  6, 10])


In [34]:
print(practice[2,2])

tensor(11)


In [36]:
print(practice[:, 2:])

tensor([[ 3,  4],
        [ 7,  8],
        [11, 12]])


In [37]:
print(practice[:2, :3])

tensor([[1, 2, 3],
        [5, 6, 7]])


In [38]:
print(practice)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
