In [1]:
import torch

In [3]:
from torch import nn

In [4]:
class CreditNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(4,2)

    def forward(self, x):
        return self.linear(x)

In [5]:
model = CreditNet()
print(model)

CreditNet(
  (linear): Linear(in_features=4, out_features=2, bias=True)
)


In [6]:
for name, param in model.named_parameters():
    print(name)
    print(param)
    print(param.shape)
    print("-" * 40)

linear.weight
Parameter containing:
tensor([[-0.4111, -0.3914,  0.3896, -0.2165],
        [ 0.3639,  0.0747,  0.0381,  0.2835]], requires_grad=True)
torch.Size([2, 4])
----------------------------------------
linear.bias
Parameter containing:
tensor([ 0.1806, -0.4162], requires_grad=True)
torch.Size([2])
----------------------------------------


In [7]:
x = torch.tensor([
    [50000.0, 29.0, 10000.0, 1.0],
    [70000.0, 31.0, 7000.0, 0.0]

])

output = model(x)
print(output)
print(output.shape)

tensor([[-16670.9219,  18579.3516],
        [-26062.5742,  25743.7578]], grad_fn=<AddmmBackward0>)
torch.Size([2, 2])


In [8]:
single_x = torch.tensor([[50000.0, 29.0, 10000.0, 1.0]])
print(single_x.shape)

single_output = model(single_x)
print(single_output)
print(single_output.shape)

torch.Size([1, 4])
tensor([[-16670.9219,  18579.3516]], grad_fn=<AddmmBackward0>)
torch.Size([1, 2])
