In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [4]:
print(x.shape)

torch.Size([12])


In [5]:
x_reshaped = x.reshape(3,4)
print(x_reshaped)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [7]:
print(x_reshaped.shape)

torch.Size([3, 4])


In [8]:
x2 = x.reshape(2,6)

print(x2)

print(x2.shape)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])


In [9]:
x3 = x.reshape(3, -1)

In [10]:
print(x3)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [11]:
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [12]:
print(x3.shape)

torch.Size([3, 4])


In [13]:
x4 = x.reshape(-1, 2)

In [14]:
print(x4)
print(x4.shape)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])
torch.Size([6, 2])


In [16]:
matrix = torch.tensor([
    [1,2,3],
    [4,5,6]
])

In [17]:
flat = matrix.reshape(-1)

In [18]:
print(flat)

tensor([1, 2, 3, 4, 5, 6])


In [19]:
print(flat.shape)

torch.Size([6])
