In [1]:
import torch

In [3]:
x = torch.arange(8)

In [4]:
x_reshaped = x.reshape(2,4)

In [5]:
print(x_reshaped)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])


In [7]:
y = torch.arange(16)

In [8]:
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])


In [9]:
y_reshaped = y.reshape(4,4)

In [10]:
print(y_reshaped)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [11]:
z = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [12]:
flat = z.flatten()

In [13]:
print(flat)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
