In [15]:
import torch

In [16]:
# Tensor Shape Debugging

## Section 1: Create scalar, vector, matrix, and 3D tensor

In [17]:
import torch

# Scalar
scalar = torch.tensor(7)

# Vector
vector = torch.tensor([1, 2, 3, 4, 5])

# Matrix
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

# 3D Tensor
tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Scalar:\n", scalar)
print("\nVector:\n", vector)
print("\nMatrix:\n", matrix)
print("\n3D Tensor:\n", tensor_3d)

Scalar:
 tensor(7)

Vector:
 tensor([1, 2, 3, 4, 5])

Matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])

3D Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [18]:
## Section 2: Print shape, ndim, and dtype

In [19]:
print("SCALAR")
print("shape:", scalar.shape)
print("ndim:", scalar.ndim)
print("dtype:", scalar.dtype)

print("\nVECTOR")
print("shape:", vector.shape)
print("ndim:", vector.ndim)
print("dtype:", vector.dtype)

print("\nMATRIX")
print("shape:", matrix.shape)
print("ndim:", matrix.ndim)
print("dtype:", matrix.dtype)

print("\n3D TENSOR")
print("shape:", tensor_3d.shape)
print("ndim:", tensor_3d.ndim)
print("dtype:", tensor_3d.dtype)

SCALAR
shape: torch.Size([])
ndim: 0
dtype: torch.int64

VECTOR
shape: torch.Size([5])
ndim: 1
dtype: torch.int64

MATRIX
shape: torch.Size([2, 3])
ndim: 2
dtype: torch.int64

3D TENSOR
shape: torch.Size([2, 2, 2])
ndim: 3
dtype: torch.int64


In [20]:
## Section 3: Index rows, columns, and slices

In [21]:
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Matrix:\n", x)

print("\nFirst row:")
print(x[0])

print("\nSecond column:")
print(x[:, 1])

print("\nTop-left 2x2 block:")
print(x[0:2, 0:2])

print("\nRows 0 and 1, columns 1 and 2:")
print(x[0:2, 1:3])

Matrix:
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

First row:
tensor([10, 20, 30])

Second column:
tensor([20, 50, 80])

Top-left 2x2 block:
tensor([[10, 20],
        [40, 50]])

Rows 0 and 1, columns 1 and 2:
tensor([[20, 30],
        [50, 60]])


In [22]:
## Section 4: Reshape tensors

In [23]:
a = torch.arange(8)
print("Original a:")
print(a)
print("Shape:", a.shape)

a_reshaped = a.reshape(2, 4)
print("\nReshaped to 2x4:")
print(a_reshaped)
print("Shape:", a_reshaped.shape)

b = torch.arange(16).reshape(4, 4)
print("\n4x4 tensor:")
print(b)
print("Shape:", b.shape)

c = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("\nOriginal 3x3 tensor:")
print(c)
print("Shape:", c.shape)

c_flat = c.flatten()
print("\nFlattened tensor:")
print(c_flat)
print("Shape:", c_flat.shape)

Original a:
tensor([0, 1, 2, 3, 4, 5, 6, 7])
Shape: torch.Size([8])

Reshaped to 2x4:
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
Shape: torch.Size([2, 4])

4x4 tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
Shape: torch.Size([4, 4])

Original 3x3 tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Shape: torch.Size([3, 3])

Flattened tensor:
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
Shape: torch.Size([9])


In [24]:
## Section 5: Broadcasting examples that work and fail

In [25]:
# Vector + scalar
vector = torch.tensor([1, 2, 3])
scalar = torch.tensor(10)

print("Vector + Scalar:")
print(vector + scalar)

# Matrix + row vector
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])

row = torch.tensor([10, 20, 30])

print("\nMatrix + Row Vector:")
print(matrix + row)

# Matrix + column vector
column = torch.tensor([
    [10],
    [20]
])

print("\nMatrix + Column Vector:")
print(matrix + column)

Vector + Scalar:
tensor([11, 12, 13])

Matrix + Row Vector:
tensor([[11, 22, 33],
        [14, 25, 36]])

Matrix + Column Vector:
tensor([[11, 12, 13],
        [24, 25, 26]])


In [26]:
## Section 6: Dot product and matrix multiplication

In [ ]:
# Dot product
v1 = torch.tensor([1, 2, 3])
v2 = torch.tensor([4, 5, 6])

dot = torch.dot(v1, v2)
print("Dot product:")
print(dot)

# Matrix multiplication
m1 = torch.tensor([
    [1, 2],
    [3, 4]
])

m2 = torch.tensor([
    [5, 6],
    [7, 8]
])

matmul_result = torch.matmul(m1, m2)
print("\nMatrix multiplication:")
print(matmul_result)

# Failing matrix multiplication example
bad1 = torch.rand(2, 3)
bad2 = torch.rand(2, 2)

print("\nBad matrix multiplication shapes:")
print("bad1 shape:", bad1.shape)
print("bad2 shape:", bad2.shape)

# This will fail because 3 != 2
print(torch.matmul(bad1, bad2))




Dot product:
tensor(32)

Matrix multiplication:
tensor([[19, 22],
        [43, 50]])

Bad matrix multiplication shapes:
bad1 shape: torch.Size([2, 3])
bad2 shape: torch.Size([2, 2])


RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x2)

: 

In [34]:
A = torch.rand(2, 3)
B = torch.rand(2)

print("A shape:", A.shape)
print("B shape:", B.shape)

# This will fail
print(A + B)

A shape: torch.Size([2, 3])
B shape: torch.Size([2])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1