In [1]:
import torch

In [2]:
scalar = torch.tensor(5)

In [3]:
print(scalar)

tensor(5)


In [4]:
print(scalar.shape)

torch.Size([])


In [5]:
print(scalar.ndim)

0


In [6]:
vector = torch.tensor([1,2,3,4])

In [7]:
print(vector)

tensor([1, 2, 3, 4])


In [8]:
print(vector.shape)

torch.Size([4])


In [9]:
print(vector.ndim)

1


In [10]:
matrix = torch.tensor([[1,2], [3,4], [5,6]])

In [11]:
print(matrix)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [12]:
print(matrix.shape)

torch.Size([3, 2])


In [13]:
print(matrix.ndim)

2


In [14]:
tensor_3d = torch.tensor([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])

In [15]:
print(tensor_3d)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [16]:
print(tensor_3d.shape)

torch.Size([2, 2, 2])


In [17]:
print(tensor_3d.ndim)

3


In [18]:
x = torch.tensor([1,2,3])

y = torch.tensor([1.0, 2.0, 3.0])

print(x.dtype)
print(y.dtype)

torch.int64
torch.float32


In [19]:
zeros = torch.zeros((2,3))

ones = torch.ones((2,3))

random_tensor = torch.rand((2,3))

print(zeros)
print(ones)
print(random_tensor)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6404, 0.9859, 0.5343],
        [0.8583, 0.6531, 0.8598]])
